### ISSUE TITLE
Review blog posts for </blockquote> at EOL

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/librarycarpentry.github.io#32]
Follow-up to #31.

- [x] Reg-ex through all `.md` files in [`/_posts`](https://github.com/LibraryCarpentry/librarycarpentry.github.io/tree/master/_posts) using `^<blockquote class="twitter-tweet".*</blockquote>$` or similar 
- [x] check [LC blog](https://librarycarpentry.org/blog/) for paragraphs covered by Twitter cards
- [x] if yes, move `</blockquote>` to new line

**Comment by libcce** [comment]
@katrinleinweber just checked https://github.com/LibraryCarpentry/librarycarpentry.github.io/search?q=blockquote&unscoped_q=blockquote you don't need to do this it seems. There were only a few cases where tweets were embedded and I got around it by switching to .html instead of .md (before you found a way, thanks).

**Comment by katrinleinweber** [comment]
But, but [Calgary](https://librarycarpentry.org/blog/2018/09/report-from-calgary-workshops/) 😢 I feel a special connection to that city 😉

**Comment by libcce** [comment]
Thanks, I didn't catch this! And I don't understand why this is failing, I thought I had fixed it but it might've been before we transitioned to the new site. Thanks for catching this one too! And I ❤️ Calgary as well. The training we held there has led to many new instructors helping with Library Carpentry 😃
