### ISSUE TITLE
Generate workshops.yml from parsing index.md of identified workshop sites

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/librarycarpentry.github.io#66]
[Currently, `_data/workshops.yml` is produced manually](https://github.com/LibraryCarpentry/librarycarpentry.github.io/blame/64bfcec0bd5baf818ff66353efef9e9228e76bb4/). However, it's mostly a copy of [a workshop's metadata block in its `index.md`](https://github.com/evamarik/2019-11-frankfurt/blame/0f746a60291db849e14c566eba07ef5be3b4911c/index.md).

If we could use a parser for that format, we could use `_data/workshops.yml` to only aggregate the repo URLs (or even only `namespace/repo` assuming `https://github.com/` as a base-URL) and have [the workshop list](https://librarycarpentry.org/upcoming_workshops/) auto-generated before (or somehow during) the page build process.

If anyone has an idea how to do the latter, or which parser to use, please share it here!

**Comment by libcce** [comment]
@katrinleinweber we were using this issue as a placeholder https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/1 but the good news is that there are updates coming that address this issue https://carpentries.org/blog/2019/08/workshop-request-form-updates-teaser/. So no need for a fix, the fix is coming 😄

**Comment by katrinleinweber** [comment]
Cool :-)
